### PR TITLE
Replace .transfer for SafeTransferETH

### PR DESCRIPTION
**Pull request by stevennevins**
I noticed some C-E-I violations around the ETH transfers that we would need to address

This PR only swaps out the `.transfer()` function for the more compatible safeTransferETH from solmate

### CODE REVIEW

**Review by mehtaculous — APPROVED** [review]
Looks good to me

Does it make sense to also address the CEI issues in this PR as well?

**Comment by stevennevins** [comment]
I think it’s better to keep the PRs that touch a relatively large number of files concise for now

**Comment by stevennevins** [comment]
We should also use a safeTransfer library for ERC20, which would handle missing return booleans.  ERC721 and ERC1155, we don't need to

This safeTransferETH maintains compatibility with receiving ETH to certain smart contracts (most importantly sc-wallets)

**Review by xflpt — APPROVED** [review]

**Comment by stevennevins** [comment]
Will follow up with another

**Pull request merged**
