### PR TITLE
Remove Usage of _msgData and _msgSender

### PR DESCRIPTION
**Pull request by stevennevins**
Should probably merge prettier PR first

### CODE REVIEW

**Comment by xflpt** [comment]
This is already included in the refactoring PR, it is kinda of duplicate I think.

**Review by mehtaculous — APPROVED** [review]
Looks good to me

**Comment by mehtaculous** [comment]
> This is already included in the refactoring PR, it is kinda of duplicate I think.

hmm it seems the refactoring PR is replacing `tx.origin` with `msg.sender`

this PR is replacing `_msgSender()` with `msg.sender`

both are definitely important but there may also be some overlap..

**Comment by xflpt** [comment]
You're right, I actually intended to remove all of them as part of the PR to do some cleaning :)

**Comment by stevennevins** [comment]
It looks like this was taken care of in https://github.com/fxhash/fxhash-evm-contracts/pull/17

**Pull request closed without merging**
